<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Demande extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_demandes'] = $this->Educazad_model->get_multiple('tb_im_demandes', array(), 'tb_im_demandes.demande_id','DESC');

        $data['_view'] = 'demandes/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_intrants', array(), 'tb_im_intrants.intrant_id','DESC');

        $this->load->library('form_validation');

        $this->form_validation->set_rules('intrant_sid','Intrant SID','required');
        $this->form_validation->set_rules('date_demandee','date_demandee','required');
        $this->form_validation->set_rules('qte_demandee','qte_demandee','required');
        $this->form_validation->set_rules('benef_nom','benef_nom','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');

            $code_intrant = strstr($this->input->post('intrant_sid'), '-', true);
            $intrant_sid = (!empty($code_intrant)) ? $code_intrant : $this->input->post('intrant_sid');
            //new quqntity
            $new_sortie_qte=$this->input->post('qte_demandee');
            $params = array(
                'benef_nom' => $this->input->post('benef_nom'),
                'benef_postnom' => $this->input->post('benef_postnom'),
                'benef_prenom' => $this->input->post('benef_prenom'),
                'benef_phone' => $this->input->post('benef_phone'),
                'benef_adresse' => $this->input->post('benef_adresse'),
                'qte_demandee' => $new_sortie_qte,
                'date_demandee' => $this->input->post('date_demandee'),
                'date_ajout' =>  $current_datetime,
                'intrant_sid' => $intrant_sid,
            );
            $existing_quantity_stock = $this->Educazad_model->get_unique('tb_im_intrants', array('intrant_id'=>$intrant_sid))->qte_stock;

            if ($new_sortie_qte > $existing_quantity_stock){
                $data['error_sortie'] = "Vous avez saisie une quantité très élevée par rapport à la quantité de stock. 
                                        Le stock actuel de l'intrant selectionné est de $existing_quantity_stock. ";
                $data['_view'] = 'demandes/add';
                $this->load->view('layouts/main',$data);
            }else {
                $new_qte_stock = $existing_quantity_stock - $new_sortie_qte;
                $param_intrant = array('qte_stock' => $new_qte_stock);

                $this->Educazad_model->update_data('tb_im_intrants',$param_intrant, array('intrant_id'=>$intrant_sid));
                $this->Educazad_model->insert_data('tb_im_demandes',$params);
                redirect('demande/index');
            }
        }
        else
        {
            $data['_view'] = 'demandes/add';
            $this->load->view('layouts/main',$data);
        }
    }
}