<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Entree extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_entrees'] = $this->Educazad_model->get_multiple('tb_im_entrees', array(), 'tb_im_entrees.entree_id','DESC');

        $data['_view'] = 'entrees/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_intrants', array(), 'tb_im_intrants.intrant_id','DESC');

        $this->load->library('form_validation');

        $this->form_validation->set_rules('intrant_sid','Intrant SID','required');
        $this->form_validation->set_rules('date_entree','date_entree','required');
        $this->form_validation->set_rules('qte_entree','qte_entree','required');
        $this->form_validation->set_rules('fss_nom','fss_nom','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');

            $code_intrant = strstr($this->input->post('intrant_sid'), '-', true);
            $intrant_sid = (!empty($code_intrant)) ? $code_intrant : $this->input->post('intrant_sid');
            //new quqntity
            $new_entry_qte=$this->input->post('qte_entree');
            $params = array(
                'fss_nom' => $this->input->post('fss_nom'),
                'fss_postnom' => $this->input->post('fss_postnom'),
                'fss_prenom' => $this->input->post('fss_prenom'),
                'fss_phone' => $this->input->post('fss_phone'),
                'fss_adresse' => $this->input->post('fss_adresse'),
                'qte_entree' => $new_entry_qte,
                'date_entree' => $this->input->post('date_entree'),
                'date_ajout' =>  $current_datetime,
                'intrant_sid' => $intrant_sid,
            );
            $existing_quantity_stock = $this->Educazad_model->get_unique('tb_im_intrants', array('intrant_id'=>$intrant_sid))->qte_stock;
            $new_qte_stock=$existing_quantity_stock+$new_entry_qte;
            $param_intrant = array('qte_stock' => $new_qte_stock);

            $this->Educazad_model->insert_data('tb_im_entrees',$params);
            $this->Educazad_model->update_data('tb_im_intrants',$param_intrant, array('intrant_id'=>$intrant_sid));
            redirect('entree/index');
        }
        else
        {
            $data['_view'] = 'entrees/add';
            $this->load->view('layouts/main',$data);
        }
    }
}